Do not use transformers v4.34.0 for now
v4.34.0 has introduced a major tokenizer refactor, which seems to
break some of the models. For example, pfnet/plamo-13b evaluation
fails with the following error:

    AttributeError: 'PlamoTokenizer' object has no attribute 'sp_model'

Also see https://github.com/huggingface/transformers/releases/tag/v4.34.0